version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/frontend-react"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
