"""
Domain — 集中管理所有常數與閾值。
避免散落在各模組中的 magic numbers / magic strings。
"""

__all__ = [
    "ACCOUNT_TYPE_OPTIONS",
    "ANALYTICS_DEFAULT_LOOKBACK_DAYS",
    "ANALYTICS_MIN_DAYS_FOR_RATIOS",
    "ANALYTICS_MIN_DOWNSIDE_SAMPLES",
    "ANALYTICS_RISK_FREE_RATE",
    "ANALYTICS_TRADING_DAYS_PER_YEAR",
    "BACKFILL_DEFAULT_MOAT",
    "BACKFILL_HISTORY_PERIOD",
    "BACKFILL_MARKET_STATUS",
    "BACKFILL_MIN_HISTORY_DAYS",
    "BACKFILL_SAMPLE_INTERVAL",
    "BACKTEST_CACHE_TTL",
    "BACKTEST_FP_WINDOW",
    "BACKTEST_MAX_LOOKBACK_DAYS",
    "BACKTEST_MIN_SAMPLES_HIGH",
    "BACKTEST_MIN_SAMPLES_MEDIUM",
    "BACKTEST_WINDOWS",
    "BENCHMARK_TICKERS",
    "BETA_CACHE_MAXSIZE",
    "BETA_CACHE_TTL",
    "BETA_MIN_HISTORY_PERIODS",
    "BIAS_OVERHEATED_THRESHOLD",
    "BIAS_OVERSOLD_THRESHOLD",
    "BIAS_WEAKENING_THRESHOLD",
    "CATEGORY_DISPLAY_ORDER",
    "CATEGORY_FALLBACK_BETA",
    "CATEGORY_ICON",
    "CATEGORY_LIQUIDITY_ORDER",
    "CATEGORY_RSI_OFFSET",
    "CNN_FG_API_URL",
    "CNN_FG_EXTREME_FEAR",
    "CNN_FG_FEAR",
    "CNN_FG_GREED",
    "CNN_FG_NEUTRAL_HIGH",
    "CNN_FG_REQUEST_TIMEOUT",
    "COINGECKO_API_URL",
    "COINGECKO_RATE_LIMIT_CPS",
    "CRYPTO_CACHE_MAXSIZE",
    "CRYPTO_CACHE_TTL",
    "CRYPTO_QUANTITY_MAX_DECIMALS",
    "CRYPTO_VOLATILITY_EXTREME_PCT",
    "CRYPTO_VOLATILITY_HIGH_PCT",
    "CURL_CFFI_IMPERSONATE",
    "CURRENCY_REGION_MAP",
    "DEFAULT_ACCOUNT_NAME",
    "DEFAULT_DISPLAY_CURRENCY",
    "DEFAULT_GURUS",
    "DEFAULT_IMPORT_CATEGORY",
    "DEFAULT_LANGUAGE",
    "DEFAULT_MARKET",
    "DEFAULT_NOTIFICATION_PREFERENCES",
    "DEFAULT_NOTIFICATION_RATE_LIMITS",
    "DEFAULT_USER_ID",
    "DEFAULT_WEBHOOK_THESIS",
    "DISK_BETA_TTL",
    "DISK_CRYPTO_TTL",
    "DISK_DIVIDEND_TTL",
    "DISK_EARNINGS_TTL",
    "DISK_ETF_HOLDINGS_TTL",
    "DISK_ETF_SECTOR_WEIGHTS_TTL",
    "DISK_EXCHANGE_TTL",
    "DISK_FEAR_GREED_TTL",
    "DISK_FOREX_HISTORY_LONG_TTL",
    "DISK_FOREX_HISTORY_TTL",
    "DISK_FOREX_TTL",
    "DISK_FUNDAMENTALS_TTL",
    "DISK_GURU_FILING_TTL",
    "DISK_KEY_BETA",
    "DISK_KEY_CRYPTO",
    "DISK_KEY_DIVIDEND",
    "DISK_KEY_DIVIDEND_EVENTS",
    "DISK_KEY_EARNINGS",
    "DISK_KEY_ETF_HOLDINGS",
    "DISK_KEY_ETF_SECTOR_WEIGHTS",
    "DISK_KEY_EXCHANGE",
    "DISK_KEY_FEAR_GREED",
    "DISK_KEY_FOREX",
    "DISK_KEY_FOREX_HISTORY",
    "DISK_KEY_FOREX_HISTORY_LONG",
    "DISK_KEY_FUNDAMENTALS",
    "DISK_KEY_GURU_FILING",
    "DISK_KEY_MOAT",
    "DISK_KEY_NAME",
    "DISK_KEY_PRICE_HISTORY",
    "DISK_KEY_PRICE_PAIR",
    "DISK_KEY_ROGUE_WAVE",
    "DISK_KEY_SECTOR",
    "DISK_KEY_SIGNALS",
    "DISK_KEY_STOCK_SPLIT",
    "DISK_KEY_YF_INFO",
    "DISK_MOAT_FAILURE_TTL",
    "DISK_MOAT_PERSISTENT_TTL",
    "DISK_MOAT_TTL",
    "DISK_NAME_TTL",
    "DISK_PRICE_HISTORY_TTL",
    "DISK_PRICE_PAIR_TTL",
    "DISK_ROGUE_WAVE_TTL",
    "DISK_SECTOR_TTL",
    "DISK_SIGNALS_TTL",
    "DISK_YF_INFO_TTL",
    "DIVIDEND_CACHE_MAXSIZE",
    "DIVIDEND_CACHE_TTL",
    "DIVIDEND_LOOKBACK_DAYS",
    "DRAWDOWN_EPSILON",
    "DRAWDOWN_PERIOD_THRESHOLD_DEFAULT",
    "DRIFT_ACK_EXPIRE_DAYS",
    "DRIFT_THRESHOLD_PCT",
    "EARNINGS_CACHE_MAXSIZE",
    "EARNINGS_CACHE_TTL",
    "ENRICHED_CACHE_MAXSIZE",
    "ENRICHED_CACHE_TTL",
    "ENRICHED_PER_TICKER_TIMEOUT",
    "ENRICHED_THREAD_POOL_SIZE",
    "EQUITY_CATEGORIES",
    "ERROR_ACCOUNT_NOT_FOUND",
    "ERROR_BACKTEST_DATA_NOT_FOUND",
    "ERROR_BACKTEST_SIGNAL_UNKNOWN",
    "ERROR_CATEGORY_UNCHANGED",
    "ERROR_DIGEST_IN_PROGRESS",
    "ERROR_FX_WATCH_NOT_FOUND",
    "ERROR_GURU_FILING_NOT_FOUND",
    "ERROR_GURU_NOT_FOUND",
    "ERROR_HOLDING_NOT_FOUND",
    "ERROR_INSUFFICIENT_BALANCE",
    "ERROR_INTERNAL_ERROR",
    "ERROR_INVALID_INPUT",
    "ERROR_INVALID_SCENARIO_DROP",
    "ERROR_PREFERENCES_UPDATE_FAILED",
    "ERROR_PROFILE_NOT_FOUND",
    "ERROR_SCAN_IN_PROGRESS",
    "ERROR_STOCK_ALREADY_ACTIVE",
    "ERROR_STOCK_ALREADY_EXISTS",
    "ERROR_STOCK_ALREADY_INACTIVE",
    "ERROR_STOCK_NOT_FOUND",
    "ERROR_SYNC_IN_PROGRESS",
    "ERROR_TELEGRAM_NOT_CONFIGURED",
    "ERROR_TELEGRAM_SEND_FAILED",
    "ERROR_TRANSACTION_NOT_FOUND",
    "ETF_HOLDINGS_CACHE_MAXSIZE",
    "ETF_HOLDINGS_CACHE_TTL",
    "ETF_TOP_N",
    "FEAR_GREED_CACHE_MAXSIZE",
    "FEAR_GREED_CACHE_TTL",
    "FG_BREADTH_MULT",
    "FG_COMPONENT_FAILURE_COOLDOWN_SECONDS",
    "FG_COMPONENT_WEIGHTS",
    "FG_HYG_TICKER",
    "FG_JUNK_BOND_MULT",
    "FG_LOOKBACK_DAYS",
    "FG_MA_WINDOW",
    "FG_MOMENTUM_MA_MULT",
    "FG_MOMENTUM_RSI_WEIGHT",
    "FG_PRICE_STRENGTH_MULT",
    "FG_QQQ_TICKER",
    "FG_RSP_TICKER",
    "FG_SAFE_HAVEN_MULT",
    "FG_SECTOR_ROTATION_MULT",
    "FG_SPY_TICKER",
    "FG_TLT_TICKER",
    "FG_VIX_BASE",
    "FG_VIX_OFFSET",
    "FG_VIX_SLOPE",
    "FG_XLP_TICKER",
    "FINMIND_API_URL",
    "FINMIND_CIRCUIT_BREAKER_COOLDOWN",
    "FINMIND_CIRCUIT_BREAKER_THRESHOLD",
    "FINMIND_LOOKBACK_DAYS",
    "FINMIND_REQUEST_TIMEOUT",
    "FOREX_CACHE_MAXSIZE",
    "FOREX_CACHE_TTL",
    "FOREX_HISTORY_CACHE_MAXSIZE",
    "FOREX_HISTORY_CACHE_TTL",
    "FOREX_HISTORY_LONG_CACHE_MAXSIZE",
    "FOREX_HISTORY_LONG_CACHE_TTL",
    "FUNDAMENTALS_CACHE_MAXSIZE",
    "FUNDAMENTALS_CACHE_TTL",
    "FX_DAILY_SPIKE_PCT",
    "FX_HISTORY_PERIOD",
    "FX_LONG_TERM_PERIOD",
    "FX_LONG_TERM_TREND_PCT",
    "FX_SHORT_TERM_SWING_PCT",
    "FX_WATCH_DEFAULT_ALERT_ON_CONSECUTIVE",
    "FX_WATCH_DEFAULT_ALERT_ON_RECENT_HIGH",
    "FX_WATCH_DEFAULT_CONSECUTIVE_DAYS",
    "FX_WATCH_DEFAULT_RECENT_HIGH_DAYS",
    "FX_WATCH_DEFAULT_REMINDER_HOURS",
    "FX_WATCH_FORCE_REFRESH_COOLDOWN_SECONDS",
    "FX_WATCH_HIGH_RECENCY_THRESHOLD",
    "FX_WATCH_RECENT_HIGH_TOLERANCE_PCT",
    "FX_WATCH_TREND_LONG_WINDOW",
    "FX_WATCH_TREND_SHORT_WINDOW",
    "FX_WATCH_TREND_SIDEWAYS_THRESHOLD",
    "GENERIC_ERROR_MESSAGE",
    "GENERIC_PREFERENCES_ERROR",
    "GENERIC_TELEGRAM_ERROR",
    "GENERIC_VALIDATION_ERROR",
    "GENERIC_WEBHOOK_ERROR",
    "GURU_BACKFILL_FILING_COUNT",
    "GURU_BACKFILL_YEARS",
    "GURU_BACKTEST_CACHE_TTL",
    "GURU_BACKTEST_MAX_QUARTERS",
    "GURU_FILING_CACHE_MAXSIZE",
    "GURU_FILING_CACHE_TTL",
    "GURU_FILING_DEADLINES",
    "GURU_HEATMAP_CACHE_TTL",
    "GURU_HOLDING_CHANGES_DISPLAY_LIMIT",
    "GURU_HOLDING_CHANGE_THRESHOLD_PCT",
    "GURU_TOP_HOLDINGS_COUNT",
    "HOLDING_QUANTITY_EPSILON",
    "IDECO_LIMITS",
    "INSIGHT_CONCENTRATION_THRESHOLD",
    "INSIGHT_EXCELLENT_HEALTH_SCORE",
    "INSIGHT_MODERATE_DRAWDOWN_THRESHOLD",
    "INSIGHT_OUTPERFORMANCE_THRESHOLD",
    "INSIGHT_POOR_HEALTH_SCORE",
    "INSIGHT_SEVERE_DRAWDOWN_THRESHOLD",
    "INSIGHT_STRONG_SHARPE",
    "INSIGHT_UNDERPERFORMANCE_THRESHOLD",
    "INSTITUTIONAL_HOLDERS_TOP_N",
    "JP_VI_BASE",
    "JP_VI_OFFSET",
    "JP_VI_SLOPE",
    "LANGUAGE_LABELS",
    "LATEST_SCAN_LOGS_DEFAULT_LIMIT",
    "MA60_WINDOW",
    "MA200_DEEP_DEVIATION_THRESHOLD",
    "MA200_WINDOW",
    "MARGIN_TREND_QUARTERS",
    "MARKET_BEARISH_MAX_PCT",
    "MARKET_BULLISH_MAX_PCT",
    "MARKET_NEUTRAL_MAX_PCT",
    "MARKET_STRONG_BULLISH_MAX_PCT",
    "MAX_IMPORT_ROWS",
    "MAX_UPLOAD_BYTES",
    "MIN_CLOSE_PRICES_FOR_CHANGE",
    "MIN_HISTORY_DAYS_FOR_SIGNALS",
    "MOAT_CACHE_MAXSIZE",
    "MOAT_CACHE_TTL",
    "MOAT_MARGIN_DETERIORATION_THRESHOLD",
    "MOAT_PERSISTENT_FAILURE_THRESHOLD",
    "NIKKEI_VI_TICKER",
    "NISA_LIMITS",
    "NISA_RESTORATION_POLICY",
    "NOTIFICATION_TYPES",
    "NOTIFICATION_TYPE_GURU_ALERTS",
    "POSITION_VERIFY_EPSILON",
    "PREWARM_BATCH_TIMEOUT",
    "PREWARM_REFRESH_INTERVAL",
    "PRICE_ALERT_COOLDOWN_HOURS",
    "PRICE_HISTORY_CACHE_MAXSIZE",
    "PRICE_HISTORY_CACHE_TTL",
    "RADAR_CATEGORIES",
    "REBALANCE_CACHE_MAXSIZE",
    "REBALANCE_CACHE_TTL",
    "REMOVAL_REASON_UNKNOWN",
    "RESONANCE_CACHE_TTL",
    "ROGUE_WAVE_BIAS_PERCENTILE",
    "ROGUE_WAVE_CACHE_MAXSIZE",
    "ROGUE_WAVE_CACHE_TTL",
    "ROGUE_WAVE_HISTORY_PERIOD",
    "ROGUE_WAVE_MIN_HISTORY_DAYS",
    "ROGUE_WAVE_VOLUME_RATIO_THRESHOLD",
    "RSI_APPROACHING_BUY_THRESHOLD",
    "RSI_CONTRARIAN_BUY_THRESHOLD",
    "RSI_DEEP_VALUE_THRESHOLD",
    "RSI_OVERBOUGHT",
    "RSI_OVERSOLD",
    "RSI_PERIOD",
    "RSI_WEAKENING_THRESHOLD",
    "SCAN_HISTORY_DEFAULT_LIMIT",
    "SCAN_L1_WARM_THRESHOLD",
    "SCAN_STALE_SECONDS",
    "SCAN_STALE_SECONDS_OFF_HOURS",
    "SCAN_THREAD_POOL_SIZE",
    "SECONDS_PER_DAY",
    "SEC_EDGAR_ARCHIVES_BASE_URL",
    "SEC_EDGAR_BASE_URL",
    "SEC_EDGAR_RATE_LIMIT_CPS",
    "SEC_EDGAR_REQUEST_TIMEOUT",
    "SEC_EDGAR_USER_AGENT",
    "SIGNALS_CACHE_MAXSIZE",
    "SIGNALS_CACHE_TTL",
    "SKIP_MOAT_CATEGORIES",
    "SKIP_PRICE_FETCH_CATEGORIES",
    "SKIP_RSI_CATEGORIES",
    "SP500_TICKER",
    "STOCK_CATEGORIES",
    "STOCK_SPLIT_CACHE_MAXSIZE",
    "STOCK_SPLIT_CACHE_TTL",
    "STOCK_SPLIT_LOOKBACK_DAYS",
    "STRESS_DISCLAIMER",
    "STRESS_EMPTY_PAIN_LABEL",
    "STRESS_PAIN_LEVELS",
    "SUPPORTED_CURRENCIES",
    "SUPPORTED_LANGUAGES",
    "TAX_WRAPPER_OPTIONS",
    "TELEGRAM_API_URL",
    "TELEGRAM_MAX_MESSAGE_LENGTH",
    "TELEGRAM_REQUEST_TIMEOUT",
    "TICKER_MARKET_MAP",
    "TOKUTEI_TAX_RATE",
    "TWII_TICKER",
    "TW_VOL_BASE",
    "TW_VOL_OFFSET",
    "TW_VOL_SLOPE",
    "VIX_EXTREME_FEAR",
    "VIX_FEAR",
    "VIX_GREED",
    "VIX_HISTORY_PERIOD",
    "VIX_NEUTRAL_LOW",
    "VIX_SCORE_BREAKPOINTS",
    "VIX_SCORE_CEILING",
    "VIX_SCORE_CEILING_VIX",
    "VIX_SCORE_FLOOR",
    "VIX_SCORE_FLOOR_VIX",
    "VIX_TICKER",
    "VOLUME_RATIO_LONG_DAYS",
    "VOLUME_RATIO_SHORT_DAYS",
    "VOLUME_SURGE_THRESHOLD",
    "VOLUME_THIN_THRESHOLD",
    "WEBHOOK_ACTION_REGISTRY",
    "WEBHOOK_MISSING_TICKER",
    "WEEKLY_DIGEST_LOOKBACK_DAYS",
    "WITHDRAWAL_MIN_SELL_VALUE",
    "XRAY_ACK_STEP_PCT",
    "XRAY_SINGLE_STOCK_WARN_PCT",
    "XRAY_SKIP_CATEGORIES",
    "YFINANCE_HISTORY_PERIOD",
    "YFINANCE_RATE_LIMIT_CPS",
    "YFINANCE_RETRY_ATTEMPTS",
    "YFINANCE_RETRY_WAIT_MAX",
    "YFINANCE_RETRY_WAIT_MIN",
    "YF_CONNECT_TIMEOUT",
    "YF_INFO_CACHE_MAXSIZE",
    "YF_INFO_CACHE_TTL",
    "YF_READ_TIMEOUT",
]

# ---------------------------------------------------------------------------
# Imports from domain sub-modules — all symbols remain accessible via this
# module so that existing "from domain.core.constants import X" calls continue
# to work unchanged.
# ---------------------------------------------------------------------------
from domain.core._constants_market import (
    BETA_CACHE_MAXSIZE,
    BETA_CACHE_TTL,
    CATEGORY_FALLBACK_BETA,
    CNN_FG_API_URL,
    CNN_FG_EXTREME_FEAR,
    CNN_FG_FEAR,
    CNN_FG_GREED,
    CNN_FG_NEUTRAL_HIGH,
    CNN_FG_REQUEST_TIMEOUT,
    CRYPTO_CACHE_MAXSIZE,
    CRYPTO_CACHE_TTL,
    CRYPTO_QUANTITY_MAX_DECIMALS,
    CRYPTO_VOLATILITY_EXTREME_PCT,
    CRYPTO_VOLATILITY_HIGH_PCT,
    CURL_CFFI_IMPERSONATE,
    CURRENCY_REGION_MAP,
    DEFAULT_MARKET,
    DISK_BETA_TTL,
    DISK_CRYPTO_TTL,
    DISK_ETF_HOLDINGS_TTL,
    DISK_ETF_SECTOR_WEIGHTS_TTL,
    DISK_FEAR_GREED_TTL,
    DISK_FOREX_HISTORY_LONG_TTL,
    DISK_FOREX_HISTORY_TTL,
    DISK_FOREX_TTL,
    DISK_KEY_BETA,
    DISK_KEY_CRYPTO,
    DISK_KEY_DIVIDEND,
    DISK_KEY_DIVIDEND_EVENTS,
    DISK_KEY_EARNINGS,
    DISK_KEY_ETF_HOLDINGS,
    DISK_KEY_ETF_SECTOR_WEIGHTS,
    DISK_KEY_FEAR_GREED,
    DISK_KEY_FOREX,
    DISK_KEY_FOREX_HISTORY,
    DISK_KEY_FOREX_HISTORY_LONG,
    DISK_KEY_FUNDAMENTALS,
    DISK_KEY_MOAT,
    DISK_KEY_PRICE_HISTORY,
    DISK_KEY_ROGUE_WAVE,
    DISK_KEY_SIGNALS,
    DISK_KEY_STOCK_SPLIT,
    DISK_KEY_YF_INFO,
    DISK_PRICE_HISTORY_TTL,
    DISK_ROGUE_WAVE_TTL,
    ETF_HOLDINGS_CACHE_MAXSIZE,
    ETF_HOLDINGS_CACHE_TTL,
    ETF_TOP_N,
    FEAR_GREED_CACHE_MAXSIZE,
    FEAR_GREED_CACHE_TTL,
    FG_BREADTH_MULT,
    FG_COMPONENT_FAILURE_COOLDOWN_SECONDS,
    FG_COMPONENT_WEIGHTS,
    FG_HYG_TICKER,
    FG_JUNK_BOND_MULT,
    FG_LOOKBACK_DAYS,
    FG_MA_WINDOW,
    FG_MOMENTUM_MA_MULT,
    FG_MOMENTUM_RSI_WEIGHT,
    FG_PRICE_STRENGTH_MULT,
    FG_QQQ_TICKER,
    FG_RSP_TICKER,
    FG_SAFE_HAVEN_MULT,
    FG_SECTOR_ROTATION_MULT,
    FG_SPY_TICKER,
    FG_TLT_TICKER,
    FG_VIX_BASE,
    FG_VIX_OFFSET,
    FG_VIX_SLOPE,
    FG_XLP_TICKER,
    FINMIND_API_URL,
    FINMIND_CIRCUIT_BREAKER_COOLDOWN,
    FINMIND_CIRCUIT_BREAKER_THRESHOLD,
    FINMIND_LOOKBACK_DAYS,
    FINMIND_REQUEST_TIMEOUT,
    FOREX_CACHE_MAXSIZE,
    FOREX_CACHE_TTL,
    FOREX_HISTORY_CACHE_MAXSIZE,
    FOREX_HISTORY_CACHE_TTL,
    FOREX_HISTORY_LONG_CACHE_MAXSIZE,
    FOREX_HISTORY_LONG_CACHE_TTL,
    FX_DAILY_SPIKE_PCT,
    FX_HISTORY_PERIOD,
    FX_LONG_TERM_PERIOD,
    FX_LONG_TERM_TREND_PCT,
    FX_SHORT_TERM_SWING_PCT,
    FX_WATCH_DEFAULT_ALERT_ON_CONSECUTIVE,
    FX_WATCH_DEFAULT_ALERT_ON_RECENT_HIGH,
    FX_WATCH_DEFAULT_CONSECUTIVE_DAYS,
    FX_WATCH_DEFAULT_RECENT_HIGH_DAYS,
    FX_WATCH_DEFAULT_REMINDER_HOURS,
    FX_WATCH_FORCE_REFRESH_COOLDOWN_SECONDS,
    FX_WATCH_HIGH_RECENCY_THRESHOLD,
    FX_WATCH_RECENT_HIGH_TOLERANCE_PCT,
    FX_WATCH_TREND_LONG_WINDOW,
    FX_WATCH_TREND_SHORT_WINDOW,
    FX_WATCH_TREND_SIDEWAYS_THRESHOLD,
    JP_VI_BASE,
    JP_VI_OFFSET,
    JP_VI_SLOPE,
    NIKKEI_VI_TICKER,
    PREWARM_BATCH_TIMEOUT,
    PRICE_HISTORY_CACHE_MAXSIZE,
    PRICE_HISTORY_CACHE_TTL,
    ROGUE_WAVE_BIAS_PERCENTILE,
    ROGUE_WAVE_CACHE_MAXSIZE,
    ROGUE_WAVE_CACHE_TTL,
    ROGUE_WAVE_HISTORY_PERIOD,
    ROGUE_WAVE_MIN_HISTORY_DAYS,
    ROGUE_WAVE_VOLUME_RATIO_THRESHOLD,
    STRESS_DISCLAIMER,
    STRESS_EMPTY_PAIN_LABEL,
    STRESS_PAIN_LEVELS,
    SUPPORTED_CURRENCIES,
    TICKER_MARKET_MAP,
    TW_VOL_BASE,
    TW_VOL_OFFSET,
    TW_VOL_SLOPE,
    TWII_TICKER,
    VIX_EXTREME_FEAR,
    VIX_FEAR,
    VIX_GREED,
    VIX_HISTORY_PERIOD,
    VIX_NEUTRAL_LOW,
    VIX_SCORE_BREAKPOINTS,
    VIX_SCORE_CEILING,
    VIX_SCORE_CEILING_VIX,
    VIX_SCORE_FLOOR,
    VIX_SCORE_FLOOR_VIX,
    VIX_TICKER,
    VOLUME_SURGE_THRESHOLD,
    VOLUME_THIN_THRESHOLD,
    XRAY_SINGLE_STOCK_WARN_PCT,
    XRAY_SKIP_CATEGORIES,
    YF_CONNECT_TIMEOUT,
    YF_READ_TIMEOUT,
    YFINANCE_RETRY_ATTEMPTS,
    YFINANCE_RETRY_WAIT_MAX,
    YFINANCE_RETRY_WAIT_MIN,
)
from domain.core._constants_nisa import (
    IDECO_LIMITS,
    NISA_LIMITS,
    NISA_RESTORATION_POLICY,
    TAX_WRAPPER_OPTIONS,
    TOKUTEI_TAX_RATE,
)
from domain.core._constants_portfolio import (
    ACCOUNT_TYPE_OPTIONS,
    ANALYTICS_DEFAULT_LOOKBACK_DAYS,
    ANALYTICS_MIN_DAYS_FOR_RATIOS,
    ANALYTICS_MIN_DOWNSIDE_SAMPLES,
    ANALYTICS_RISK_FREE_RATE,
    ANALYTICS_TRADING_DAYS_PER_YEAR,
    BENCHMARK_TICKERS,
    CATEGORY_DISPLAY_ORDER,
    CATEGORY_ICON,
    CATEGORY_LIQUIDITY_ORDER,
    DEFAULT_ACCOUNT_NAME,
    DEFAULT_DISPLAY_CURRENCY,
    DEFAULT_LANGUAGE,
    DEFAULT_NOTIFICATION_PREFERENCES,
    DEFAULT_NOTIFICATION_RATE_LIMITS,
    DEFAULT_USER_ID,
    DRAWDOWN_EPSILON,
    DRAWDOWN_PERIOD_THRESHOLD_DEFAULT,
    DRIFT_ACK_EXPIRE_DAYS,
    DRIFT_THRESHOLD_PCT,
    EQUITY_CATEGORIES,
    ERROR_ACCOUNT_NOT_FOUND,
    ERROR_BACKTEST_DATA_NOT_FOUND,
    ERROR_BACKTEST_SIGNAL_UNKNOWN,
    ERROR_CATEGORY_UNCHANGED,
    ERROR_DIGEST_IN_PROGRESS,
    ERROR_FX_WATCH_NOT_FOUND,
    ERROR_GURU_FILING_NOT_FOUND,
    ERROR_GURU_NOT_FOUND,
    ERROR_HOLDING_NOT_FOUND,
    ERROR_INSUFFICIENT_BALANCE,
    ERROR_INTERNAL_ERROR,
    ERROR_INVALID_INPUT,
    ERROR_INVALID_SCENARIO_DROP,
    ERROR_PREFERENCES_UPDATE_FAILED,
    ERROR_PROFILE_NOT_FOUND,
    ERROR_SCAN_IN_PROGRESS,
    ERROR_STOCK_ALREADY_ACTIVE,
    ERROR_STOCK_ALREADY_EXISTS,
    ERROR_STOCK_ALREADY_INACTIVE,
    ERROR_STOCK_NOT_FOUND,
    ERROR_SYNC_IN_PROGRESS,
    ERROR_TELEGRAM_NOT_CONFIGURED,
    ERROR_TELEGRAM_SEND_FAILED,
    ERROR_TRANSACTION_NOT_FOUND,
    GENERIC_ERROR_MESSAGE,
    GENERIC_PREFERENCES_ERROR,
    GENERIC_TELEGRAM_ERROR,
    GENERIC_VALIDATION_ERROR,
    GENERIC_WEBHOOK_ERROR,
    HOLDING_QUANTITY_EPSILON,
    INSIGHT_CONCENTRATION_THRESHOLD,
    INSIGHT_EXCELLENT_HEALTH_SCORE,
    INSIGHT_MODERATE_DRAWDOWN_THRESHOLD,
    INSIGHT_OUTPERFORMANCE_THRESHOLD,
    INSIGHT_POOR_HEALTH_SCORE,
    INSIGHT_SEVERE_DRAWDOWN_THRESHOLD,
    INSIGHT_STRONG_SHARPE,
    INSIGHT_UNDERPERFORMANCE_THRESHOLD,
    LANGUAGE_LABELS,
    MAX_IMPORT_ROWS,
    MAX_UPLOAD_BYTES,
    NOTIFICATION_TYPES,
    POSITION_VERIFY_EPSILON,
    RADAR_CATEGORIES,
    SP500_TICKER,
    STOCK_CATEGORIES,
    SUPPORTED_LANGUAGES,
    WITHDRAWAL_MIN_SELL_VALUE,
    XRAY_ACK_STEP_PCT,
)
from domain.core._constants_scan import (
    BACKFILL_DEFAULT_MOAT,
    BACKFILL_HISTORY_PERIOD,
    BACKFILL_MARKET_STATUS,
    BACKFILL_MIN_HISTORY_DAYS,
    BACKFILL_SAMPLE_INTERVAL,
    BACKTEST_CACHE_TTL,
    BACKTEST_FP_WINDOW,
    BACKTEST_MAX_LOOKBACK_DAYS,
    BACKTEST_MIN_SAMPLES_HIGH,
    BACKTEST_MIN_SAMPLES_MEDIUM,
    BACKTEST_WINDOWS,
    BETA_MIN_HISTORY_PERIODS,
    BIAS_OVERHEATED_THRESHOLD,
    BIAS_OVERSOLD_THRESHOLD,
    BIAS_WEAKENING_THRESHOLD,
    CATEGORY_RSI_OFFSET,
    COINGECKO_API_URL,
    COINGECKO_RATE_LIMIT_CPS,
    DEFAULT_IMPORT_CATEGORY,
    DEFAULT_WEBHOOK_THESIS,
    DISK_DIVIDEND_TTL,
    DISK_EARNINGS_TTL,
    DISK_FUNDAMENTALS_TTL,
    DISK_MOAT_FAILURE_TTL,
    DISK_MOAT_PERSISTENT_TTL,
    DISK_MOAT_TTL,
    DISK_SIGNALS_TTL,
    DISK_YF_INFO_TTL,
    DIVIDEND_CACHE_MAXSIZE,
    DIVIDEND_CACHE_TTL,
    DIVIDEND_LOOKBACK_DAYS,
    EARNINGS_CACHE_MAXSIZE,
    EARNINGS_CACHE_TTL,
    ENRICHED_CACHE_MAXSIZE,
    ENRICHED_CACHE_TTL,
    ENRICHED_PER_TICKER_TIMEOUT,
    ENRICHED_THREAD_POOL_SIZE,
    FUNDAMENTALS_CACHE_MAXSIZE,
    FUNDAMENTALS_CACHE_TTL,
    INSTITUTIONAL_HOLDERS_TOP_N,
    LATEST_SCAN_LOGS_DEFAULT_LIMIT,
    MA60_WINDOW,
    MA200_DEEP_DEVIATION_THRESHOLD,
    MA200_WINDOW,
    MARGIN_TREND_QUARTERS,
    MARKET_BEARISH_MAX_PCT,
    MARKET_BULLISH_MAX_PCT,
    MARKET_NEUTRAL_MAX_PCT,
    MARKET_STRONG_BULLISH_MAX_PCT,
    MIN_CLOSE_PRICES_FOR_CHANGE,
    MIN_HISTORY_DAYS_FOR_SIGNALS,
    MOAT_CACHE_MAXSIZE,
    MOAT_CACHE_TTL,
    MOAT_MARGIN_DETERIORATION_THRESHOLD,
    MOAT_PERSISTENT_FAILURE_THRESHOLD,
    PREWARM_REFRESH_INTERVAL,
    PRICE_ALERT_COOLDOWN_HOURS,
    REBALANCE_CACHE_MAXSIZE,
    REBALANCE_CACHE_TTL,
    REMOVAL_REASON_UNKNOWN,
    RESONANCE_CACHE_TTL,
    RSI_APPROACHING_BUY_THRESHOLD,
    RSI_CONTRARIAN_BUY_THRESHOLD,
    RSI_DEEP_VALUE_THRESHOLD,
    RSI_OVERBOUGHT,
    RSI_OVERSOLD,
    RSI_PERIOD,
    RSI_WEAKENING_THRESHOLD,
    SCAN_HISTORY_DEFAULT_LIMIT,
    SCAN_L1_WARM_THRESHOLD,
    SCAN_STALE_SECONDS,
    SCAN_STALE_SECONDS_OFF_HOURS,
    SCAN_THREAD_POOL_SIZE,
    SECONDS_PER_DAY,
    SIGNALS_CACHE_MAXSIZE,
    SIGNALS_CACHE_TTL,
    SKIP_MOAT_CATEGORIES,
    SKIP_PRICE_FETCH_CATEGORIES,
    SKIP_RSI_CATEGORIES,
    STOCK_SPLIT_CACHE_MAXSIZE,
    STOCK_SPLIT_CACHE_TTL,
    STOCK_SPLIT_LOOKBACK_DAYS,
    VOLUME_RATIO_LONG_DAYS,
    VOLUME_RATIO_SHORT_DAYS,
    WEEKLY_DIGEST_LOOKBACK_DAYS,
    YF_INFO_CACHE_MAXSIZE,
    YF_INFO_CACHE_TTL,
    YFINANCE_HISTORY_PERIOD,
    YFINANCE_RATE_LIMIT_CPS,
)

# ---------------------------------------------------------------------------
# Telegram
# ---------------------------------------------------------------------------
TELEGRAM_API_URL = "https://api.telegram.org/bot{token}/sendMessage"
TELEGRAM_REQUEST_TIMEOUT = 10
TELEGRAM_MAX_MESSAGE_LENGTH = 4096


# ---------------------------------------------------------------------------
WEBHOOK_MISSING_TICKER = "webhook.missing_ticker"  # i18n key

# ---------------------------------------------------------------------------
# Webhook Action Registry — single source of truth for AI agent actions
# ---------------------------------------------------------------------------
WEBHOOK_ACTION_REGISTRY: dict[str, dict] = {
    "help": {
        "description": "List all supported webhook actions and their parameters",
        "requires_ticker": False,
    },
    "summary": {
        "description": "Portfolio health overview (plain text)",
        "requires_ticker": False,
    },
    "dashboard": {
        "description": "Portfolio + market overview in one call",
        "requires_ticker": False,
    },
    "signals": {
        "description": "Technical indicators for a ticker (RSI, MA, Bias)",
        "requires_ticker": True,
    },
    "analyze": {
        "description": "Full stock analysis (signals + moat + fundamentals)",
        "requires_ticker": True,
    },
    "scan": {
        "description": "Trigger background full scan (results via Telegram)",
        "requires_ticker": False,
    },
    "moat": {
        "description": "Gross margin YoY analysis for a ticker",
        "requires_ticker": True,
    },
    "alerts": {
        "description": "List price alerts for a ticker",
        "requires_ticker": True,
    },
    "add_stock": {
        "description": "Add a stock to the watchlist",
        "requires_ticker": True,
        "params": {
            "ticker": "str (required)",
            "category": "StockCategory (Trend_Setter|Moat|Growth|Mutual_Fund|Bond|Crypto|Cash|ETF)",
            "thesis": "str (investment thesis)",
            "tags": "list[str] (e.g. ['AI', 'Semiconductor'])",
        },
    },
    "fear_greed": {
        "description": "Current Fear & Greed Index (VIX + CNN composite)",
        "requires_ticker": False,
    },
    "withdraw": {
        "description": "Smart withdrawal plan (Liquidity Waterfall)",
        "requires_ticker": False,
        "params": {
            "amount": "float (required, target withdrawal amount)",
            "currency": "str (display currency, default USD)",
        },
    },
    "fx_watch": {
        "description": "Check FX watch configs & send Telegram alerts (with cooldown)",
        "requires_ticker": False,
    },
    "stock_splits": {
        "description": "Check stock splits for held tickers and notify/apply updates",
        "requires_ticker": False,
    },
    "dividends": {
        "description": "Check dividends for held tickers and notify/apply updates",
        "requires_ticker": False,
    },
    "drift_alerts": {
        "description": "Run portfolio drift checks and send alert summaries",
        "requires_ticker": False,
    },
    "acknowledge_drift": {
        "description": "Acknowledge one drift category to suppress repeated alerts",
        "requires_ticker": False,
        "params": {
            "category": "str (required — allocation category name)",
            "drift_pct": "float (optional — current drift percentage points)",
            "display_currency": "str (optional — default USD)",
        },
    },
    "acknowledge_xray": {
        "description": "Acknowledge one X-Ray symbol to suppress repeated alerts",
        "requires_ticker": False,
        "params": {
            "symbol": "str (required — concentrated underlying symbol)",
            "total_weight_pct": "float (optional — current portfolio weight percentage)",
            "display_currency": "str (optional — default USD)",
        },
    },
    "guru_sync": {
        "description": "Trigger 13F filing sync for all tracked gurus (EDGAR fetch)",
        "requires_ticker": False,
    },
    "guru_summary": {
        "description": "Send latest guru holding changes digest via Telegram",
        "requires_ticker": False,
    },
    "transactions": {
        "description": "List recent transactions (buy/sell/dividend/deposit/withdrawal)",
        "requires_ticker": False,
        "params": {
            "ticker": "str (optional — filter by ticker)",
            "account_id": "int (optional — filter by account)",
            "start": "str (optional — YYYY-MM-DD start date)",
            "end": "str (optional — YYYY-MM-DD end date)",
            "limit": "int (optional — default 10, max 50)",
        },
    },
    "add_transaction": {
        "description": "Record a new transaction",
        "requires_ticker": True,
        "params": {
            "type": "str (required — BUY/SELL/DIVIDEND/DEPOSIT/WITHDRAWAL/OPENING_BALANCE/ADJUSTMENT/STOCK_SPLIT/TRANSFER_IN/TRANSFER_OUT)",
            "account_id": "int (required — account identifier)",
            "quantity": "float (required)",
            "price": "float (optional — per-unit price)",
            "total_amount": "float (required — total transaction value)",
            "date": "str (required — YYYY-MM-DD)",
        },
    },
    "accounts": {
        "description": "List accounts with holdings count per account",
        "requires_ticker": False,
    },
    "analytics": {
        "description": "Portfolio risk metrics: Sharpe, Sortino, max drawdown, volatility",
        "requires_ticker": False,
        "params": {
            "start": "str (optional — YYYY-MM-DD start date)",
            "end": "str (optional — YYYY-MM-DD end date)",
        },
    },
    "insights": {
        "description": "Natural language portfolio insights and suggestions",
        "requires_ticker": False,
        "params": {
            "display_currency": "str (optional — default USD)",
        },
    },
    "quota": {
        "description": "NISA/iDeCo 額度狀態查詢",
        "requires_ticker": False,
        "description_en": "NISA/iDeCo quota status (annual/lifetime remaining, restoration forecast)",
        "params": {
            "year": "int (optional — fiscal year, default current year)",
        },
    },
}


# ---------------------------------------------------------------------------
# Smart Money Tracker (大師足跡追蹤)
# ---------------------------------------------------------------------------
GURU_HOLDING_CHANGE_THRESHOLD_PCT = 20.0  # +/-20% = significant change
GURU_TOP_HOLDINGS_COUNT = 10
GURU_HOLDING_CHANGES_DISPLAY_LIMIT = 20  # default limit for per-guru holding changes
GURU_FILING_DEADLINES = ["02-14", "05-15", "08-14", "11-14"]
SEC_EDGAR_BASE_URL = "https://data.sec.gov"
SEC_EDGAR_ARCHIVES_BASE_URL = "https://www.sec.gov"
# TODO(Phase 2): override with env var SEC_EDGAR_USER_AGENT in sec_edgar.py;
# SEC policy requires a real contact email in the User-Agent header.
SEC_EDGAR_USER_AGENT = "Folio/1.0 (folio@example.com)"
SEC_EDGAR_RATE_LIMIT_CPS = 10.0  # SEC allows 10 req/sec
SEC_EDGAR_REQUEST_TIMEOUT = 15

# Default Gurus (CIK codes)
DEFAULT_GURUS = [
    {
        "name": "Berkshire Hathaway Inc",
        "cik": "0001067983",
        "display_name": "Warren Buffett",
        "style": "VALUE",
        "tier": "TIER_1",
    },
    {
        "name": "Bridgewater Associates, LP",
        "cik": "0001350694",
        "display_name": "Ray Dalio",
        "style": "MACRO",
        "tier": "TIER_1",
    },
    {
        "name": "Citadel Advisors LLC",
        "cik": "0001423053",
        "display_name": "Ken Griffin",
        "style": "QUANT",
        "tier": "TIER_1",
    },
    {
        "name": "Renaissance Technologies LLC",
        "cik": "0001037389",
        "display_name": "Renaissance Technologies",
        "style": "QUANT",
        "tier": "TIER_1",
    },
    {
        "name": "Baupost Group LLC",
        "cik": "0001061768",
        "display_name": "Seth Klarman",
        "style": "VALUE",
        "tier": "TIER_1",
    },
    {
        "name": "Oaktree Capital Management, L.P.",
        "cik": "0001535581",
        "display_name": "Howard Marks",
        "style": "VALUE",
        "tier": "TIER_1",
    },
    {
        "name": "ARK Investment Management LLC",
        "cik": "0001603466",
        "display_name": "Cathie Wood",
        "style": "GROWTH",
        "tier": "TIER_2",
    },
    {
        "name": "Pershing Square Capital Management",
        "cik": "0001336528",
        "display_name": "Bill Ackman",
        "style": "ACTIVIST",
        "tier": "TIER_2",
    },
    {
        "name": "Scion Asset Management, LLC",
        "cik": "0001649339",
        "display_name": "Michael Burry",
        "style": "VALUE",
        "tier": "TIER_2",
    },
    {
        "name": "Appaloosa Management LP",
        "cik": "0001656456",
        "display_name": "David Tepper",
        "style": "MULTI_STRATEGY",
        "tier": "TIER_2",
    },
    {
        "name": "Himalaya Capital Management LLC",
        "cik": "0001598220",
        "display_name": "Li Lu",
        "style": "VALUE",
        "tier": "TIER_2",
    },
    {
        "name": "Gotham Asset Management, LLC",
        "cik": "0001452934",
        "display_name": "Joel Greenblatt",
        "style": "QUANT",
        "tier": "TIER_2",
    },
    {
        "name": "Soros Fund Management LLC",
        "cik": "0001029160",
        "display_name": "George Soros",
        "style": "MACRO",
        "tier": "TIER_1",
    },
    {
        "name": "Social Capital Holdings Inc.",
        "cik": "0001705696",
        "display_name": "Chamath Palihapitiya",
        "style": "GROWTH",
        "tier": "TIER_3",
    },
]

# Notification
NOTIFICATION_TYPE_GURU_ALERTS = "guru_alerts"

GURU_BACKFILL_YEARS = 5  # 回填歷史 13F 資料的年數
GURU_BACKFILL_FILING_COUNT = 20  # 每位大師最多取回 20 筆申報（約 5 年）
GURU_BACKTEST_CACHE_TTL = 3600  # 1 hour
GURU_HEATMAP_CACHE_TTL = 300  # 5 minutes
GURU_BACKTEST_MAX_QUARTERS = 12

# Cache
GURU_FILING_CACHE_MAXSIZE = 50
GURU_FILING_CACHE_TTL = 86400  # 24h (13F data is quarterly)
DISK_GURU_FILING_TTL = 604800  # 7 days
DISK_KEY_GURU_FILING = "guru_filing"
DISK_SECTOR_TTL = 2592000  # 30 days (sectors change very rarely)
DISK_KEY_SECTOR = "sector"
DISK_NAME_TTL = 2592000  # 30 days (company names change very rarely)
DISK_KEY_NAME = "name"
DISK_EXCHANGE_TTL = 2592000  # 30 days (exchange metadata is mostly static)
DISK_KEY_EXCHANGE = "exchange"
DISK_KEY_PRICE_PAIR = "price_pair"
DISK_PRICE_PAIR_TTL = 0  # permanent — historical close prices are immutable

# ---------------------------------------------------------------------------
